variables:
    POSTGRES_PASSWORD: "zup"
    POSTGRES_USER: "zup"
    POSTGRES_DB: "zup"
    SHARED_BUFFERS: 128MB

stages:
    - build

before_script:
    - export POSTGRES_NAME="postgres$CI_BUILD_ID"
    - export REDIS_NAME="redis$CI_BUILD_ID"
    - export API_NAME="zup-api-$CI_BUILD_ID"
    - export BUILDER_NAME="zup-painel-builder-$CI_BUILD_ID"

setup:
    stage: build
    script:
        - echo API_URL=http://localhost:3000 >> api.env
        - echo WEB_URL=http://localhost:3000 >> api.env
        - echo SMTP_ADDRESS=smtp.sendgrid.net >> api.env
        - echo SMTP_PORT=587 >> api.env
        - echo SMTP_USER=zup >> api.env
        - echo SMTP_PASS=CBsowzZ7kq2d >> api.env
        - echo SMTP_TTLS=true >> api.env
        - echo SMTP_AUTH=plain >> api.env
        - echo REDIS_URL=redis://redis:6379 >> api.env
        - echo RACK_ENV=production >> api.env
        - echo DATABASE_URL=postgis://zup:zup@postgres:5432/zup >> api.env
        - export API_BRANCH=$CI_BUILD_REF_NAME
        - REDIS_CID=$(docker run --privileged -d --name $REDIS_NAME redis:2.8)
        - docker pull ntxcode/zup-api:$API_BRANCH || docker pull ntxcode/zup-api:latest && export API_BRANCH="latest"
        - docker run --rm --link $REDIS_NAME:redis --link $POSTGRES_NAME:postgres -a stdout -a stderr --env-file api.env ntxcode/zup-api:$API_BRANCH bundle exec rake db:schema:load
        - "docker run --rm --link $REDIS_NAME:redis -a stdout -a stderr --env-file api.env ntxcode/zup-api:$API_BRANCH /bin/bash -c \"bundle exec rake db:seed WITH_FAKE_DATA=true\""
        - docker run --rm --link $REDIS_NAME:redis -a stdout -a stderr --env-file api.env --name $API_NAME -P ntxcode/zup-api:$API_BRANCH &
        - export API_ENDPOINT=$(docker port $API_NAME 80)
        - curl http://$API_ENDPOINT/feature_flags &

build:
    stage: build
    script:
        - echo API_URL=http://$(docker port $API_NAME 80) >> .env
        - echo MAP_LAT=-23.549671 >> .env
        - echo MAP_LNG=-46.6321713 >> .env
        - echo MAP_ZOOM=11 >> .env
        - echo DEFAULT_CITY="São Bernado do Campo" >> .env
        - echo DEFAULT_STATE=SP >> .env
        - echo DEFAULT_COUNTRY=Brasil >> .env
        - "echo PAINEL_URL=http://localhost:9001 >> .env"
        - echo USER_EMAIL=tecnologia@ntxdev.com.br >> .env
        - echo USER_PASSWORD=123456 >> .env
        - echo FLOWS_ENABLED=true >> .env
        - docker build -t $BUILDER_NAME .
        - export BUILD_CID=$(docker run -a stdout -a stderr --net=host --name $BUILDER_NAME)
        - docker rm -f $POSTGRES_NAME
        - docker rm -f $REDIS_NAME
        - docker rm -f $API_NAME
        - docker rm -f $BUILDER_NAME
        - docker rmi -f $BUILDER_NAME
        - git config --global user.name 'Gitlab CI'
        - git config --global user.email 'tecnologia@ntdev.com.br'
        - rm -rf zup-web || true
        - git clone --depth 1 --branch $CI_BUILD_REF_NAME https://$DOCKER_USERNAME:$DOCKER_PASSWORD@gitlab.com/ntxcode/zup-web.git || git clone --depth 1 --branch master https://$DOCKER_USERNAME:$DOCKER_PASSWORD@gitlab.com/ntxcode/zup-web.git
        - cd zup-web
        - "[[ $(git symbolic-ref --short -q HEAD) = $CI_BUILD_REF_NAME ]] || git checkout -b $CI_BUILD_REF_NAME"
        - rm -rf zup-painel
        - cp -R ../dist ./zup-painel
        - git add --all zup-painel
        - git commit -m "Build $CI_BUILD_ID"
        - git push origin $CI_BUILD_REF_NAME
